### ISSUE TITLE
Any testing file?

### ISSUE THREAD

**Issue by HawkinsZhao** [ayush2991/DAIC-WOZ#1]
I am interesting in your great project, but is there any testing file? I think it may helps someone else to run this code on their computer.

**Comment by ayush2991** [comment]
@HawkinsZhao, Thanks for your interest in DAIC-WOZ! Unfortunately, this dataset is not public, but if you are really keen on it, you might want to participate in the 2017 version of the competition (details for the the 2016 edition https://arxiv.org/abs/1605.01600). Good luck!

**Comment by HawkinsZhao** [comment]
@ayush2991 Thanks
